spring:
  profiles:
    active: test

  config:
    import:
      - logging.yml
      - database.yml
      - security.yml
      - monitoring.yml

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: asc
    operationsSorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
    enabled: true
    version: openapi_3_1
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---
####################
###   🧪 TESTS   ###
####################
spring.config.activate.on-profile: test

spring:
  output:
    ansi:
      enabled: always

---
####################
###   💻 LOCAL   ###
####################
spring.config.activate.on-profile: local

spring:
  output:
    ansi:
      enabled: always

---
####################
###    🛠 DEV    ###
####################
spring.config.activate.on-profile: dev

spring:
  output:
    ansi:
      enabled: always

---
####################
###  📦 Staging  ###
####################
spring.config.activate.on-profile: staging

---
####################
###   💎 PROD    ###
####################
spring.config.activate.on-profile: prod
